config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  post "admin/pos/change_garantia/:number" , to: "admin/pos#change_garantia", as: :change_garantia_admin_pos

  resources :products do
    collection do
      get :autocomplete
    end
  end
  
  namespace :admin, path: Spree.admin_path do
    resources :stock_items

    resources :reports, only: %i[index show] do # <= add this block
      collection do
        get :sales_total
        post :sales_total
        get :users
        post :users
        get :products
        post :products
        get :variants
      end
    end
  end
end

app/views/spree/admin/orders/_add_line_item.html.erb
<%= render partial: "spree/admin/variants/autocomplete", formats: :js %>

<%= render partial: "spree/admin/variants/autocomplete_line_items_stock", formats: :js %>

<div id="add-line-item" data-hook class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= Spree.t(:add_product) %></h1>
  </div>
  <div class="panel-body">
    <div data-hook="add_product_name" class="form-group">
      <%= label_tag :add_line_item_variant_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_line_item_variant_id, "", class: "variant_autocomplete fullwidth-input" %>
    </div>

    <div id="stock_details"></div>
  </div>
</div>

app/views/spree/admin/orders/_add_product.html.erb
<%= render partial: "spree/admin/variants/autocomplete", formats: :js %>
<%= render partial: "spree/admin/variants/autocomplete_stock", formats: :js %>

<div class="panel panel-default" id="add-line-item" data-hook>
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= Spree.t(:add_product) %>
    </h1>
  </div>
  <div class="panel-body">
    <div data-hook="add_product_name">
      <%= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_variant_id, "", class: "variant_autocomplete fullwidth-input" %>
    </div>

    <div id="stock_details"></div>
  </div>
</div>

app/views/spree/admin/orders/_adjustments.html.erb
<% if adjustments.eligible.exists? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= title %>
      </h1>
    </div>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th><%= Spree.t('name')%></th>
          <th><%= Spree.t('amount')%></th>
        </tr>
      </thead>
      <tbody id="order-charges" data-hook="order_details_adjustments">
        <% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td>
              <strong><%= label %>:</strong>
            </td>
            <td class="total">
              <span>
                <%= Spree::Money.new(
                  adjustments.sum(&:amount),
                  currency: adjustments.first.order.try(:currency)
                ) %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render 'spree/admin/shared/error_messages', target: @line_item %>
  <% end %>

  <% if Spree::Order.checkout_step_names.include?(:delivery) %>
    <%= render partial: "spree/admin/orders/shipment", collection: @order.shipments.order(:created_at), locals: {order: order} %>
  <% else %>
    <%= render "spree/admin/orders/line_items", order: order %>
  <% end %>

  <%= render "spree/admin/orders/adjustments",
        adjustments: @order.line_item_adjustments,
        order: order,
        title: Spree.t(:line_item_adjustments)
  %>
  <%= render "spree/admin/orders/adjustments",
        adjustments: @order.shipment_adjustments,
        order: order,
        title: Spree.t(:shipment_adjustments)
  %>
  <%= render "spree/admin/orders/adjustments",
        adjustments: @order.adjustments,
        order: order,
        title: Spree.t(:order_adjustments)
  %>

  <% if order.line_items.exists? %>
    <div class="alert alert-success" id="order-total" data-hook="order_details_total">
      <%= Spree.t(:order_total) %>:
      <strong class="order-total">
        <%= order.display_total %>
      </strong>
    </div>
  <% end %>

  <%= javascript_tag do %>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
      shipments.push(
        <%== shipment.as_json(
          root: false,
          only: [
            :id, :tracking, :number, :state, :stock_location_id
          ], include: [
            :inventory_units, :stock_location
          ]).to_json
        %>
      );
    <% end %>

    <%= render partial: 'spree/admin/shared/update_order_state', formats: [:js], handlers: [:erb] %>
  <% end %>
</div>

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= Spree.t(:order_line_items) %>
      </h1>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered line-items" data-hook="line-items">
        <thead>
          <tr>
            <th colspan="2"><%= Spree.t(:name) %></th>
            <th class="text-center"><%= Spree.t(:price) %></th>
            <th class="text-center"><%= Spree.t(:quantity) %></th>
            <th class="text-center"><%= Spree.t(:total_price) %></th>
            <th class="orders-actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
          </tr>
        </thead>
        <tbody>
          <% order.line_items.each do |item| %>
            <tr class="line-item" id="line-item-<%= item.id %>">
              <td class="line-item-image image text-center">
                <%= mini_image(item.variant) %>
              </td>
              <td class="line-item-name text-center">
                <%= item.name %>
                <br />
                <%= "(#{item.options_text})" if item.options_text.present? %>
              </td>
              <td class="line-item-price text-center"><%= item.single_money.to_html %></td>
              <td class="line-item-qty-show text-center">
                <%= item.quantity %>
              </td>
              <td class="line-item-qty-edit is-hidden">
                <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
              </td>
              <td class="line-item-total text-center"><%= line_item_shipment_price(item, item.quantity) %></td>
              <td class="cart-line-item-delete actions actions-4 text-center" data-hook="cart_line_item_delete">
                <% if can? :update, item %>
                  <%= link_to_with_icon 'arrow-left', Spree.t('actions.cancel'), "#", class: 'cancel-line-item btn btn-default btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), style: 'display: none', no_text: true %>
                  <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-line-item btn btn-success btn-sm', no_text: true, data: { :'line-item-id' => item.id, action: 'save'}, title: Spree.t('actions.save'), style: 'display: none' %>
                  <%= link_to_with_icon 'edit', Spree.t('edit'), "#", class: 'edit-line-item btn btn-primary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
                  <%= link_to_with_icon 'delete', Spree.t('delete'), "#", class: 'delete-line-item btn btn-danger btn-sm', data: { 'line-item-id' => item.id, action: 'remove'}, title: Spree.t('delete'), no_text: true %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/spree/admin/orders/_line_items_edit_form.html.erb
<div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
      <%= render 'spree/admin/shared/error_messages', target: @line_item %>
  <% end %>

  <%= render "spree/admin/orders/line_items", order: order %>
  <%= render "spree/admin/orders/adjustments",
          adjustments: @order.line_item_adjustments,
          order: order,
          title: Spree.t(:line_item_adjustments)
  %>
  <%= render "spree/admin/orders/adjustments",
          adjustments: @order.shipment_adjustments,
          order: order,
          title: Spree.t(:shipment_adjustments)
  %>
  <%= render "spree/admin/orders/adjustments",
          adjustments: @order.adjustments,
          order: order,
          title: Spree.t(:order_adjustments)
  %>

  <% if order.line_items.exists? %>
    <div class="alert alert-success" id="order-total" data-hook="order_details_total">
      <%= Spree.t(:order_total) %>: <strong class="order-total"><%= order.display_total %></strong>
    </div>
  <% end %>

  <%= javascript_tag do %>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
      shipments.push(<%== shipment.as_json(root: false, only: [:id, :tracking, :number, :state, :stock_location_id], include: [:inventory_units, :stock_location]).to_json %>);
    <% end %>

    <%= render partial: 'spree/admin/shared/update_order_state', formats: [:js], handlers: [:erb] %>
  <% end %>
</div>

app/views/spree/admin/orders/_order_actions.html.erb
<% content_for :page_actions do %>
  <% if can?(:fire, order) %>
    <%= event_links(order, events) %>
  <% end %>
  <% if can?(:resend, order) %>
    <%= button_link_to Spree.t(:resend, scope: 'admin.order.events', default: Spree.t(:resend)),
          resend_admin_order_url(order),
          method: :post,
          icon: 'envelope'
    %>
  <% end %>
<% end %>

app/views/spree/admin/orders/_risk_analysis.html.erb
<fieldset id="risk_analysis">
  <legend><%= "#{Spree.t(:risk_analysis)}: #{Spree.t(:not) unless @order.is_risky?} #{Spree.t(:risky)}" %></legend>
  <table class="table table-condensed table-bordered">
    <thead>
      <th><%= Spree.t('risk')%></th>
      <th><%= Spree.t('status')%></th>
    </thead>
    <tbody id="risk-analysis" data-hook="order_details_adjustments"  class="with-border">
      <tr class="">
        <td>
          <strong><%= Spree.t(:failed_payment_attempts) %>:</strong>
        </td>
        <td>
          <span class="label label-<%= @order.payments.failed.size > 0 ? 'void' : 'complete' %>">
            <%= link_to "#{Spree.t 'payments_count', count: @order.payments.failed.size, default: pluralize(@order.payments.failed.size, Spree.t(:payment))}", spree.admin_order_payments_path(@order) %>
          </span>
        </td>
      </tr>

      <tr>
        <td><strong><%= Spree.t(:avs_response) %>:</strong></td>
        <td>
          <span class="label label-<%= latest_payment.is_avs_risky? ? 'void' : 'complete' %>">
            <% if latest_payment.is_avs_risky? %>
              <%= "#{Spree.t(:error)}: #{avs_response_code[latest_payment.avs_response]}" %>
            <% else %>
              <%= Spree.t(:success) %>
            <% end %>
          </span>
        </td>
      </tr>

      <tr>
        <td><strong><%= Spree.t(:cvv_response) %>:</strong></td>
        <td>
          <span class="label label-<%= latest_payment.is_cvv_risky? ? 'void' : 'complete' %>">
            <% if latest_payment.is_cvv_risky? %>
              <%= "#{Spree.t(:error)}: #{cvv_response_code[latest_payment.cvv_response_code]}" %>
            <% else %>
              <%= Spree.t(:success) %>
            <% end %>
          </span>
        </td>
      </tr>
    </tbody>
  </table>
</fieldset>

app/views/spree/admin/orders/_shipment.html.erb
<div id="<%= "shipment_#{shipment.id}" %>" data-hook="admin_shipment_form" class="panel panel-default">

  <%= render partial: "spree/admin/variants/split", formats: :js %>

  <div class="panel-heading stock-location no-borderb" data-hook="stock-location">
    <h1 class="panel-title">
      <span class="shipment-number"><%= shipment.number %></span>
      -
      <span class="shipment-state"><%= Spree.t("shipment_states.#{shipment.state}") %></span>
      <%= Spree.t(:package_from) %>
      <strong class="stock-location-name" data-hook="stock-location-name">'<%= shipment.stock_location.name %>'</strong>
      <% if shipment.ready? and can? :update, shipment %>
        <%= link_to Spree.t(:ship), 'javascript:;', class: 'ship pull-right btn btn-success', data: { 'shipment-number' => shipment.number } %>
        <div class='clearfix'></div>
      <% end %>
    </h1>
  </div>

  <div class="table-responsive">
    <table class="table table-bordered stock-contents" data-hook="stock-contents">
      <thead>
        <tr>
          <th colspan="2"><%= Spree.t(:item_description) %></th>
          <th width="15%" class="text-center"><%= Spree.t(:price) %></th>
          <th width="15%" class="text-center"><%= Spree.t(:quantity) %></th>
          <th width="15%" class="text-center"><%= Spree.t(:total) %></th>
          <th class="orders-actions actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
        </tr>
      </thead>

      <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
        <%= render 'spree/admin/orders/shipment_manifest', shipment: shipment %>

        <% unless shipment.shipped? %>
          <tr class="edit-method is-hidden total">
            <td colspan="5">
              <div class="field alpha five columns">
                <%= label_tag 'selected_shipping_rate_id', Spree.t(:shipping_method) %>
                <%= select_tag :selected_shipping_rate_id,
                      options_for_select(shipment.shipping_rates.map {|sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
                      { class: 'select2', data: {'shipment-number' => shipment.number } } %>
              </div>
            </td>
            <td class="actions text-center">
              <% if can? :update, shipment %>
                <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-method btn btn-primary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
                <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-method btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
              <% end %>
            </td>
          </tr>
          <% end %>

          <tr class="show-method total">
            <% if rate = shipment.selected_shipping_rate %>
              <td colspan="4">
                <strong><%= rate.name %></strong>
              </td>
              <td class="total text-center">
                <%= shipment.display_cost %>
              </td>
            <% else %>
              <td colspan='5'><%= Spree.t(:no_shipping_method_selected) %></td>
            <% end %>

            <td class="actions text-center">
              <% if( (can? :update, shipment) and !shipment.shipped?) %>
                <%= link_to_with_icon 'edit', Spree.t('edit'), "javascript:;", class: 'edit-method with-tip btn btn-sm btn-primary', data: {action: 'edit'}, no_text: true %>
              <% end %>
            </td>
          </tr>


        <tr class="edit-tracking is-hidden total">
          <td colspan="5">
            <label><%= Spree.t(:tracking_number) %>:</label>
            <%= text_field_tag :tracking, shipment.tracking, class: "form-control" %>
          </td>
          <td class="actions">
            <% if can? :update, shipment %>
              <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-tracking btn btn-primary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
              <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-tracking btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
            <% end %>
          </td>
        </tr>

        <% if order.special_instructions.present? %>
          <tr class='special_instructions'>
            <td colspan="5">
              <strong><%= Spree.t(:special_instructions) %>:&nbsp;</strong><%= order.special_instructions %>
            </td>
          </tr>
        <% end %>

        <tr class="show-tracking total">
          <td colspan="5" class="tracking-value">
            <% if shipment.tracking.present? %>
              <strong><%= Spree.t(:tracking) %>:</strong> <%= link_to_tracking(shipment, target: '_blank') %>
            <% else %>
              <%= Spree.t(:no_tracking_present) %>
            <% end %>
          </td>
          <td class="actions text-center">
            <% if can? :update, shipment %>
              <%= link_to_with_icon 'edit', Spree.t('edit'), "#", class: 'edit-tracking btn btn-primary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to(new_admin_order_url, id: 'admin_new_order', class: "ui large green ui labeled icon button") do %>
    <i class="icon shopping cart"></i>
    <%= Spree.t(:new_order) %>
  <% end %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="date-range-filter col-xs-12 col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-xs-12 col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, class: 'datepicker datepicker-from form-control js-filterable', value: params[:q][:created_at_gt], placeholder: Spree.t(:start) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>

              </div>
              <div class="col-xs-12 col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, class: 'datepicker datepicker-to form-control js-filterable', value: params[:q][:created_at_lt], placeholder: Spree.t(:stop) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_state_eq, Spree.t(:status) %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.map {|s| [Spree.t("order_state.#{s.name}"), s.value]}, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, Spree.t(:payment_state) %>
            <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map {|s| [Spree.t("payment_states.#{s}"), s]}, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_shipment_state_eq, Spree.t(:shipment_state) %>
            <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map {|s| [Spree.t("shipment_states.#{s}"), s]}, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
            <%= f.text_field :line_items_variant_sku_eq, class: 'form-control js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_store_id_in, Spree.t(:store) %>
            <%= f.select :store_id_in, Spree::Store.order("#{Spree::Store.table_name}.name").pluck(:name, :id), { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">
          <div class="form-group">
            <%= label_tag :q_channel_eq, Spree.t(:channel) %>
            <%= f.select :channel_eq, Spree::Order.distinct.pluck(:channel), { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4">

          <div class="form-group">

            <div class="checkbox">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
                <%= Spree.t(:show_only_complete_orders) %>
              <% end %>
            </div>

            <div class="checkbox">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {checked: (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div>

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>

    <% end %>

  </div>

<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders %>

<% if @orders.any? %>
  <table class="ui compact table" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th class="center aligned"><%= sort_link @search, :completed_at,   I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th class="center aligned"><%= sort_link @search, :created_at,     I18n.t(:created_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th class="center aligned"><%= sort_link @search, :number,           I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></th>
        <th class="center aligned"><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, scope: 'activerecord.attributes.spree/order') %></th>
        <th class="center aligned"><%= sort_link @search, :state,            I18n.t(:state, scope: 'activerecord.attributes.spree/order') %></th>
        <th class="center aligned"><%= sort_link @search, :payment_state,    I18n.t(:payment_state, scope: 'activerecord.attributes.spree/order') %></th>
         <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th class="center aligned"><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, scope: 'activerecord.attributes.spree/order') %></th>
         <% end %>
        <th class="center aligned"><%= sort_link @search, :email,            I18n.t(:email, scope: 'activerecord.attributes.spree/order') %></th>
        <th class="center aligned"><%= sort_link @search, :total,            I18n.t(:total, scope: 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="center aligned actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td>
          <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
        </td>
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td class="center aligned">
          <span class="label label-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
            <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
          </span>
        </td>
        <td class="center aligned">
          <span class="label label-<%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
        </td>
        <td class="center aligned">
          <% if order.payment_state %>
            <span class="label label-<%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_payment_state_eq" data-ransack-value="<%= order.payment_state %>"></span>
          <% end %>
        </td>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td class="center aligned">
            <% if order.shipment_state %>
              <span class="label label-<%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></span>
              <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
          <% if order.user || order.email %>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
          <% end %>
        </td>
        <td class="center aligned"><%= order.display_total.to_html %></td>
        <td class='center aligned actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true if can?(:edit, order) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>