config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  post "admin/pos/change_garantia/:number" , to: "admin/pos#change_garantia", as: :change_garantia_admin_pos

  resources :products do
    collection do
      get :autocomplete
    end
  end
  
  namespace :admin, path: Spree.admin_path do
    resources :stock_items

    resources :reports, only: %i[index show] do # <= add this block
      collection do
        get :sales_total
        post :sales_total
        get :users
        post :users
        get :products
        post :products
        get :variants
      end
    end
  end
end

app/models/spree/variant.rb
# frozen_string_literal: true

module Spree
  class Variant < Spree::Base
    acts_as_paranoid
    acts_as_list scope: :product

    belongs_to :product, touch: true, class_name: 'Spree::Product', inverse_of: :variants
    belongs_to :tax_category, class_name: 'Spree::TaxCategory', optional: true

    delegate :name, :name=, :description, :slug, :available_on, :shipping_category_id,
             :meta_description, :meta_keywords, :shipping_category, to: :product

    # we need to have this callback before any dependent: :destroy associations
    # https://github.com/rails/rails/issues/3458
    before_destroy :ensure_no_line_items

    # must include this after ensure_no_line_items to make sure price won't be deleted before validation
    include Spree::DefaultPrice

    with_options inverse_of: :variant do
      has_many :inventory_units
      has_many :line_items
      has_many :stock_items, dependent: :destroy
    end

    has_many :orders, through: :line_items
    with_options through: :stock_items do
      has_many :stock_locations
      has_many :stock_movements
    end

    has_many :option_value_variants, class_name: 'Spree::OptionValueVariant'
    has_many :option_values, through: :option_value_variants, class_name: 'Spree::OptionValue'

    has_many :images, -> { order(:position) }, as: :viewable, dependent: :destroy, class_name: 'Spree::Image'

    has_many :prices,
             class_name: 'Spree::Price',
             dependent: :destroy,
             inverse_of: :variant

    before_validation :set_cost_currency

    validate :check_price

    validates :option_values, presence: true, unless: :is_master?

    with_options numericality: { greater_than_or_equal_to: 0, allow_nil: true } do
      validates :cost_price
      validates :price
    end
    validates :sku, uniqueness: { conditions: -> { where(deleted_at: nil) } }, allow_blank: true

    after_create :create_stock_items
    after_create :set_master_out_of_stock, unless: :is_master?

    after_touch :clear_in_stock_cache

    scope :in_stock, -> { joins(:stock_items).where('count_on_hand > ? OR track_inventory = ?', 0, false) }
    scope :backorderable, -> { joins(:stock_items).where(spree_stock_items: { backorderable: true }) }
    scope :in_stock_or_backorderable, -> { in_stock.or(backorderable) }

    scope :eligible, lambda {
      where(is_master: false).or(
        where(
          <<-SQL
            #{Variant.quoted_table_name}.id IN (
              SELECT MIN(#{Variant.quoted_table_name}.id) FROM #{Variant.quoted_table_name}
              GROUP BY #{Variant.quoted_table_name}.product_id
              HAVING COUNT(*) = 1
            )
          SQL
        )
      )
    }

    scope :not_discontinued, lambda {
      where(
        arel_table[:discontinue_on].eq(nil).or(
          arel_table[:discontinue_on].gteq(Time.current)
        )
      )
    }

    scope :not_deleted, -> { where("#{Spree::Variant.quoted_table_name}.deleted_at IS NULL") }

    scope :for_currency_and_available_price_amount, lambda { |currency = nil|
      currency ||= Spree::Config[:currency]
      joins(:prices).where('spree_prices.currency = ?', currency).where('spree_prices.amount IS NOT NULL').distinct
    }

    scope :active, lambda { |currency = nil|
      not_discontinued.not_deleted
                      .for_currency_and_available_price_amount(currency)
    }

    LOCALIZED_NUMBERS = %w[cost_price weight depth width height].freeze

    LOCALIZED_NUMBERS.each do |m|
      define_method("#{m}=") do |argument|
        self[m] = Spree::LocalizedNumber.parse(argument) if argument.present?
      end
    end

    self.whitelisted_ransackable_associations = %w[option_values product prices default_price]
    self.whitelisted_ransackable_attributes = %w[weight sku]

    # searchkick
    searchkick word_start: %i[sku ean name]
    scope :search_import, -> { includes(:prices, :product) }
    def search_data
      {
        sku: sku,
        ean: ean,
        price: price,
        name: product.name
      }
    end
    # scope :search_import, -> { includes(:prices, :product, :images) }
    # def search_data
    #   {
    #     sku: sku,
    #     ean: ean,
    #     price: price,
    #     name: product.name,
    #     image: Rails.application.routes.url_helpers.rails_representation_url(images.first.url(:mini), only_path: true)
    #   }
    # end

    # def product_url
    #   Spree::Core::Engine.routes.url_helpers.product_path(self)
    # end

    def available?
      !discontinued? && product.available?
    end

    def tax_category
      if self[:tax_category_id].nil?
        product.tax_category
      else
        Spree::TaxCategory.find(self[:tax_category_id])
      end
    end

    def options_text
      values = option_values.sort do |a, b|
        a.option_type.position <=> b.option_type.position
      end

      values.to_a.map! do |ov|
        "#{ov.option_type.presentation}: #{ov.presentation}"
      end

      values.to_sentence(words_connector: ', ', two_words_connector: ', ')
    end

    # Default to master name
    def exchange_name
      is_master? ? name : options_text
    end

    def descriptive_name
      is_master? ? name + ' - Master' : name + ' - ' + options_text
    end

    # use deleted? rather than checking the attribute directly. this
    # allows extensions to override deleted? if they want to provide
    # their own definition.
    def deleted?
      !!deleted_at
    end

    # Product may be created with deleted_at already set,
    # which would make AR's default finder return nil.
    # This is a stopgap for that little problem.
    def product
      Spree::Product.unscoped { super }
    end

    def options=(options = {})
      options.each do |option|
        set_option_value(option[:name], option[:value])
      end
    end

    def set_option_value(opt_name, opt_value)
      # no option values on master
      return if is_master

      option_type = Spree::OptionType.where(name: opt_name).first_or_initialize do |o|
        o.presentation = opt_name
        o.save!
      end

      current_value = option_values.detect { |o| o.option_type.name == opt_name }

      if current_value.nil?
        # then we have to check to make sure that the product has the option type
        unless product.option_types.include? option_type
          product.option_types << option_type
        end
      else
        return if current_value.name == opt_value

        option_values.delete(current_value)
      end

      option_value = Spree::OptionValue.where(option_type_id: option_type.id, name: opt_value).first_or_initialize do |o|
        o.presentation = opt_value
        o.save!
      end

      option_values << option_value
      save
    end

    def option_value(opt_name)
      option_values.detect { |o| o.option_type.name == opt_name }.try(:presentation)
    end

    def price_in(currency)
      prices.detect { |price| price.currency == currency } || prices.build(currency: currency)
    end

    def amount_in(currency)
      price_in(currency).try(:amount)
    end

    def price_modifier_amount_in(currency, options = {})
      return 0 unless options.present?

      options.keys.map do |key|
        m = "#{key}_price_modifier_amount_in".to_sym
        if respond_to? m
          send(m, currency, options[key])
        else
          0
        end
      end.sum
    end

    def price_modifier_amount(options = {})
      return 0 unless options.present?

      options.keys.map do |key|
        m = "#{key}_price_modifier_amount".to_sym
        if respond_to? m
          send(m, options[key])
        else
          0
        end
      end.sum
    end

    def name_and_sku
      "#{name} - #{sku}"
    end

    def sku_and_options_text
      "#{sku} #{options_text}".strip
    end

    def in_stock?
      Rails.cache.fetch(in_stock_cache_key) do
        total_on_hand > 0
      end
    end

    delegate :total_on_hand, :can_supply?, :backorderable?, to: :quantifier

    alias is_backorderable? backorderable?

    def purchasable?
      in_stock? || backorderable?
    end

    # Shortcut method to determine if inventory tracking is enabled for this variant
    # This considers both variant tracking flag and site-wide inventory tracking settings
    def should_track_inventory?
      track_inventory? && Spree::Config.track_inventory_levels
    end

    def track_inventory
      should_track_inventory?
    end

    def volume
      (width || 0) * (height || 0) * (depth || 0)
    end

    def dimension
      (width || 0) + (height || 0) + (depth || 0)
    end

    def discontinue!
      update_attribute(:discontinue_on, Time.current)
    end

    def discontinued?
      !!discontinue_on && discontinue_on <= Time.current
    end

    def backordered?
      total_on_hand <= 0 && stock_items.exists?(backorderable: true)
    end

    private

    def ensure_no_line_items
      if line_items.any?
        errors.add(:base, :cannot_destroy_if_attached_to_line_items)
        throw(:abort)
      end
    end

    def quantifier
      Spree::Stock::Quantifier.new(self)
    end

    def set_master_out_of_stock
      if product.master&.in_stock?
        product.master.stock_items.update_all(backorderable: false)
        product.master.stock_items.each(&:reduce_count_on_hand_to_zero)
      end
    end

    # Ensures a new variant takes the product master price when price is not supplied
    def check_price
      if price.nil? && Spree::Config[:require_master_price]
        return errors.add(:base, :no_master_variant_found_to_infer_price)  unless product&.master
        return errors.add(:base, :must_supply_price_for_variant_or_master) if self == product.master

        self.price = product.master.price
      end
      if price.present? && currency.nil?
        self.currency = Spree::Config[:currency]
      end
    end

    def set_cost_currency
      self.cost_currency = Spree::Config[:currency] if cost_currency.blank?
    end

    def create_stock_items

app/views/spree/admin/variants/_autocomplete.js.erb
<script type='text/template' id='variant_autocomplete_template'>
  <div class='variant-autocomplete-item media'>
    <figure class='variant-image media-left'>
      {{#if variant.image }}
        <img src='{{variant.image}}' class="thumbnail no-marginb" />
      {{ else }}
        <img src='<%= image_path("noimage/mini.png") %>' class="thumbnail no-marginb" />
      {{/if}}
    </figure>

    <div class='variant-details media-body'>
      <h5 class="variant-name media-heading">{{variant.name}}</h5>
      {{#if variant.option_values}}
        {{#each variant.option_values}}
          <strong>{{this.option_type_presentation}}:</strong> {{this.presentation}}<br/>
        {{/each}}
      {{/if}}
      <strong><%= Spree.t(:sku) %>:</strong> {{variant.sku}}
    </div>
  </div>
</script>

app/views/spree/admin/variants/_autocomplete_line_items_stock.js.erb
<script type='text/template' id='variant_line_items_autocomplete_stock_template'>

  <label><%= Spree.t(:select_stock) %></label>

  <table class="stock-levels table table-bordered" data-hook="stock-levels">
    <thead>
      <th><%= Spree.t(:name) %></th>
      <th class="text-center"><%= Spree.t(:count_on_hand) %></th>
      <th class="text-center"><%= Spree.t(:quantity) %></th>
      <th></th>
    </thead>
    <tbody>
      <tr>
        <td>{{variant.name}}</td>
        {{#if variant.track_inventory}}
          {{#if variant.is_orderable}}
            <td class="text-center">
              {{variant.total_on_hand}}
            </td>

            <td class="text-center">
              <input class="quantity form-control" id="variant_quantity" data-variant-id="{{variant.id}}" type="number" min="1" value="1">
            </td>
            <td class="actions actions-1 text-center">
              <button class="btn btn-sm btn-success add_variant with-tip" data-variant-id="{{variant.id}}" title="<%= Spree.t(:add) %>" data-action="add">
                <span class="icon icon-add"></span>
              </button>
            </td>
          {{else}}
            {{#if variant.is_backorderable}}
              <td class="text-center">
                {{variant.total_on_hand}} (<%= Spree.t(:backorders_allowed) %>)
              </td>

              <td class="text-center">
                <input class="quantity form-control" id="variant_quantity" data-variant-id="{{variant.id}}" type="number" min="1" value="1">
              </td>
              <td class="actions actions-1 text-center">
                <button class="btn btn-sm btn-success add_variant with-tip" data-variant-id="{{variant.id}}" title="<%= Spree.t(:add) %>" data-action="add">
                  <span class="icon icon-add"></span>
                </button>
              </td>
            {{else}}
              <td class="text-center"><%= Spree.t(:out_of_stock) %></td>
              <td class="text-center">0</td>
              <td></td>
            {{/if}}
          {{/if}}
        {{else}}
          <td class="text-center"><%= Spree.t(:doesnt_track_inventory) %></td>
          <td class="text-center">
            <input class="quantity form-control" id="variant_quantity" data-variant-id="{{variant.id}}" type="number" min="1" value="1">
          </td>
          <td class="actions actions-1 text-center">
            <button class="btn btn-sm btn-success add_variant with-tip" data-variant-id="{{variant.id}}" title="<%= Spree.t(:add) %>" data-action="add">
              <span class="icon icon-add"></span>
            </button>
          </td>
        {{/if}}
      </tr>
    </tbody>
  </table>
</script>

app/views/spree/admin/variants/_autocomplete_stock.js.erb
<script type='text/template' id='variant_autocomplete_stock_template'>

  <label><%= Spree.t(:select_stock) %></label>
  <table class="table table-condensed table-bordered stock-levels no-marginb" data-hook="stock-levels">
    <thead>
      <th><%= Spree.t(:location) %></th>
      <th><%= Spree.t(:count_on_hand) %></th>
      <th width="15%"><%= Spree.t(:quantity) %></th>
      <th class="actions"></th>
    </thead>
    <tbody>
      {{#each variant.stock_items}}
        <tr>
          <td>{{this.stock_location_name}}</td>
          {{#unless ../variant.track_inventory}}
            <td><%= Spree.t(:doesnt_track_inventory) %></td>
            <td>
              <input class="quantity form-control input-sm" id="stock_item_quantity" data-stock-location-id="{{this.stock_location_id}}" type="number" min="1" value="1">
            </td>
            <td class="actions actions-1">
              <button class="btn btn-sm btn-success add_variant with-tip" data-stock-location-id="{{this.stock_location_id}}" title="<%= Spree.t(:add) %>" data-action="add">
                <span class="icon icon-add"></span>
              </button>
            </td>
          {{else}}
            {{#if this.available}}
              <td>
                {{this.count_on_hand}}
                {{#if this.backorderable}} (<%= Spree.t(:backorders_allowed) %>) {{/if}}
              </td>
              <td>
                <input class="quantity form-control input-sm" id="stock_item_quantity" data-stock-location-id="{{this.stock_location_id}}" type="number" min="1" value="1">
              </td>
              <td class="actions actions-1">
                <button class="btn btn-sm btn-success add_variant with-tip" data-stock-location-id="{{this.stock_location_id}}" title="<%= Spree.t(:add) %>" data-action="add">
                  <span class="icon icon-add"></span>
                </button>
              </td>
            {{else}}
              <td><%= Spree.t(:out_of_stock) %></td>
              <td>0</td>
              <td></td>
            {{/if}}
          {{/unless}}
        </tr>
      {{/each}}
    </tbody>
  </table>
</script>

app/views/spree/admin/variants/_form.html.erb
<div class="row">
  <div data-hook="admin_variant_form_fields" class="col-xs-12 col-md-6">
    <div data-hook="variants">
      <% @product.option_types.each do |option_type| %>
        <div class="form-group" data-hook="presentation">
          <%= label :new_variant, option_type.presentation %>
          <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
            { include_blank: true }, { name: 'variant[option_value_ids][]', class: 'select2' } %>
        </div>
      <% end %>

      <div class="form-group" data-hook="sku">
        <%= f.label :sku, Spree.t(:sku) %>
        <%= f.text_field :sku, class: 'form-control' %>
      </div>
      <div>
        <%= f.field_container :ean, class: ['form-group'] do %>
          <%= f.label :ean, Spree.t(:ean) %>
          <%= f.text_field :ean, size: 16, class: 'form-control' %>
        <% end %>
      </div>

      <div class="form-group" data-hook="price">
        <%= f.label :price, Spree.t(:price) %>
        <%= f.text_field :price, value: number_to_currency(@variant.price, unit: ''), class: 'form-control' %>
      </div>

      <div class="form-group" data-hook="cost_price">
        <%= f.label :cost_price, Spree.t(:cost_price) %>
        <%= f.text_field :cost_price, value: number_to_currency(@variant.cost_price, unit: ''), class: 'form-control' %>
      </div>

      <div class="form-group" data-hook="tax_category">
        <%= f.label :tax_category_id, Spree.t(:tax_category) %>
        <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
      </div>

      <div class="form-group" data-hook="discontinue_on">

          <%= f.label :discontinue_on, Spree.t(:discontinue_on) %>
          <%= f.error_message_on :discontinue_on %>
          <%= f.text_field :discontinue_on, value: datepicker_field_value(@variant.discontinue_on), class: 'datepicker form-control' %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-md-6" data-hook="admin_variant_form_additional_fields">
    <% [:weight, :height, :width, :depth].each do |field| %>
      <div class="form-group" data-hook="<%= field %>"><%= f.label field, Spree.t(field) %>
        <% value = number_with_precision(@variant.send(field), precision: 2) %>
        <%= f.text_field field, value: value, class: 'form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/admin/variants/_split.js.erb
<script type='text/template' id='variant_split_template'>
  <tr class='stock-item-split' data-variant-id='{{variant.id}}'>
    <td colspan='2'>
      <%= Spree.t("move_variant_to", default: "Move {{variant.name}} to") %>
    </td>
    <td colspan='2'>
    <select name="item_stock_location" id='item_stock_location' style='width:100%;'>
      <option></option>
      <optgroup label="<%=Spree.t('existing_shipments')%>">
        {{#each shipments}}
        <option data-shipment-number='{{this.number}}' value='{{this.stock_location_id}}'>{{this.stock_location.name}}({{this.number}})</option>
        {{/each}}
      </optgroup>
      <optgroup label="<%=Spree.t('new_shipment_at_location')%>">
        {{#each variant.stock_items}}
          <option data-new-shipment='true' value='{{this.stock_location_id}}'>{{this.stock_location_name}}&nbsp({{this.count_on_hand}} on hand)</option>
        {{/each}}
      </optgroup>
      </select>
    </td>
    <td>
      <input class="quantity form-control" id="item_quantity" type="number" min="1" value="1" max="{{max_quantity}}">
    </td>
    <td class='actions'>
      <a href='#' class='cancel-split with-tip btn btn-sm btn-default' title='Cancel'>
        <span class="icon icon-arrow-left"></span>
      </a>
      <a href='#' class='save-split with-tip btn btn-sm btn-success' title='Save'>
        <span class="icon icon-save"></span>
      </a>
    </td>
  </tr>
</script>

app/views/spree/admin/variants/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :variants } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset>
    <div data-hook="admin_variant_edit_form">
      <%= render partial: 'form', locals: { f: f } %>
    </div>

    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/variants/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: {current: :variants} %>

<%# Place for new variant form %>
<div id="new_variant" data-hook></div>

<% if @variants.any? %>
  <table class="table sortable" data-sortable-link="<%= update_positions_admin_product_variants_path(@product) %>">
    <thead data-hook="variants_header">
      <tr>
        <th colspan="2"><%= Spree.t(:options) %></th>
        <th><%= Spree.t(:price) %></th>
        <th><%= Spree.t(:sku) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @variants.each do |variant| %>
      <tr id="<%= spree_dom_id variant %>" <%= 'style="color:red;"' if variant.deleted? %> data-hook="variants_row">
        <td class="move-handle">
          <% if can? :edit, variant %>
            <span class="icon icon-move handle"></span>
          <% end %>
        </td>
        <td><%= variant.options_text %></td>
        <td><%= variant.display_price.to_html %></td>
        <td><%= variant.sku %></td>
        <td class="actions actions-2 text-right">
          <%= link_to_edit(variant, no_text: true) if can?(:edit, variant) && !variant.deleted? %>
          <%= link_to_delete(variant, no_text: true) if can?(:destroy, variant) && !variant.deleted? %>
        </td>
      </tr>
      <% end %>
      <% unless @product.has_variants? %>
        <tr>
          <td colspan="5"><%= Spree.t(:none) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found alert alert-info">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Variant)) %>
    <% if can?(:create, Spree::Variant) && !@product.empty_option_values? %>
      - <%= link_to(Spree.t(:add_one), spree.new_admin_product_variant_path(@product)) %>!
    <% end %>
  </div>
<% end %>

<% if @product.empty_option_values? %>
  <% if can?(:modify, Spree::ProductOptionType) %>
    <p class='first_add_option_types no-objects-found' data-hook="first_add_option_types">
      <%= Spree.t(:to_add_variants_you_must_first_define) %>
      <%= link_to(Spree.t(:option_types), spree.admin_product_url(@product)) %>
      <% if can?(:display, Spree::OptionType) && can?([:create, :display], Spree::OptionValue) %>
        <%= Spree.t(:and) %>
        <%= link_to Spree.t(:option_values), spree.admin_option_types_url %>
      <% end %>
    </p>
  <% end %>
<% else %>
  <% content_for :page_actions do %>
    <%= button_link_to(Spree.t(:new_variant), spree.new_admin_product_variant_url(@product), { remote: :true, icon: 'add', :'data-update' => 'new_variant', class: 'btn-success', id: 'new_var_link' }) if can? :create, Spree::Variant %>
    <%= button_link_to (@deleted.blank? ? Spree.t(:show_deleted) : Spree.t(:show_active)), spree.admin_product_variants_url(@product, deleted: @deleted.blank? ? "on" : "off"), { class: 'btn-default', icon: 'filter' } %>
  <% end %>
<% end %>

app/views/spree/admin/variants/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <div class="well">
    <fieldset data-hook="admin_variant_new_form">
      <legend><%= Spree.t(:new_variant) %></legend>
      <%= render partial: 'form', locals: { f: f } %>
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </fieldset>
  </div>
<% end %>

app/views/spree/admin/variants/new.js.erb
$("#new_variant").html('<%= escape_javascript(render template: 'spree/admin/variants/new', formats: [:html], handlers: [:erb]) %>');
$(".select2").select2();
$("#new_var_link").hide();

app/views/spree/admin/variants/update.js.erb
<%= @object.as_json %>